# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Cemil Çelik
description: "Hi,I am Cemil, a data scientist with a passion for impactful solutions. My portfolio showcases recent projects that demonstrate the tangible business value I bring. Please visit my Github & LinkedIn pages or download my resume by using the links below! "
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Data Science <span style="color:#f58506"> Portfolio </span>
location: "Istanbul, Turkey"
resume_url: /docs/Cemil Celik Resume 2023.pdf
avatar_image: /img/portfolio_image.jpg

#-------------------------------
# Contact links
linkedln: "https://linkedin.com/in/cemil-çelik-0295631a9" # Add your linkedln handle
github: "https://github.com/Cemilcelik11"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

